osx_image: xcode8
language: objective-c

before_install:
  - gem update fastlane --no-ri --no-rdoc --no-document

env:
  global:
    - WORKSPACE="MetaWear/MetaWear.xcworkspace"
    - DERIVED_DATA_PATH="./MetaWear/Build"

  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=10.0" SCHEME="MetaWearUnitTests-iOS"   RUN_COVERAGE="YES"
    - DESTINATION="platform=macOS,arch=x86_64"                    SCHEME="MetaWearUnitTests-macOS" RUN_COVERAGE="NO"
    - DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"   SCHEME="MetaWearUnitTests-tvOS"  RUN_COVERAGE="NO"

script:
  - scan --workspace "$WORKSPACE" --scheme "$SCHEME" --destination "$DESTINATION" --skip_build --derived_data_path "$DERIVED_DATA_PATH" --code_coverage "$RUN_COVERAGE"

after_success:
  - if [ $RUN_COVERAGE == "YES" ]; then
      bash <(curl -s https://codecov.io/bash) -J '^MetaWear$' -D "$DERIVED_DATA_PATH";
    fi
